### ISSUE TITLE
Consistent reads are not supported on global secondary indexes

### ISSUE THREAD

**Issue by bsautner** [awslabs/dynamodb-geo#16]
Need some doc on how a table in dynamodb should be created.  I'm able to save geopoints to my table, but when i do a  queryRadius I get an error that the geo-hash index is missing.  When i create the index i get this error: 

```
Caused by: java.util.concurrent.ExecutionException: com.amazonaws.AmazonServiceException: Consistent reads are not supported on global secondary indexes (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: DM3EDOUN6B0783R7FQBPJBG1U3VV4KQNSO5AEMVJF66Q9ASUAAJG)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.amazonaws.geo.GeoDataManager.dispatchQueries(GeoDataManager.java:343)
 
```

I must be missing something in the docs on how to create the table in dynamodb.

**Comment by bsautner** [comment]
ok - i bit the bullet and ran the sample server which creates a table and provides the example i needed. Thanks
