### ISSUE TITLE
Throwing errors in case of data is >= 1 Mb

### ISSUE THREAD

**Issue by ashishitmca** [awslabs/dynamodb-geo#18]
Hi,
I have approx. 2000 records at a single area but when i increase the radius it throws exception. Can some one tell me how to paginate these results and recompile source if change in library.

Error :
24-Oct-2016 22:55:31.195 INFO [http-nio-8080-exec-1] org.apache.catalina.core.ApplicationContext.log GeoDynamoDBServlet: com.amazonaws.AmazonClientException: Querying Amazon DynamoDB failed.
	at com.amazonaws.geo.GeoDataManager.dispatchQueries(GeoDataManager.java:348)
	at com.amazonaws.geo.GeoDataManager.queryRadius(GeoDataManager.java:225)
	at com.amazonaws.geo.server.GeoDynamoDBServlet.queryRadius(GeoDynamoDBServlet.java:347)
	at com.amazonaws.geo.server.GeoDynamoDBServlet.doPost(GeoDynamoDBServlet.java:157)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: AmazonServiceException: Status Code: 400, AWS Service: AmazonDynamoDBv2, AWS Request ID: HF7JTN010QMENVE28OTL656ASVVV4KQNSO5AEMVJF66Q9ASUAAJG, AWS Error Code: ValidationException, AWS Error Message: The provided starting key is invalid
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.amazonaws.geo.GeoDataManager.dispatchQueries(GeoDataManager.java:343)
	... 26 more

> Caused by: AmazonServiceException: Status Code: 400, AWS Service: AmazonDynamoDBv2, AWS Request ID: HF7JTN010QMENVE28OTL656ASVVV4KQNSO5AEMVJF66Q9ASUAAJG, AWS Error Code: ValidationException, AWS Error Message: The provided starting key is invalid

	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:679)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:350)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:202)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:1217)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.query(AmazonDynamoDBClient.java:834)
	at com.amazonaws.geo.dynamodb.internal.DynamoDBManager.queryGeohash(DynamoDBManager.java:95)
	at com.amazonaws.geo.GeoDataManager$GeoQueryThread.run(GeoDataManager.java:418)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more

**Comment by eugenehp** [comment]
@ashishitmca were you able to find a solution for this?

**Comment by arujit** [comment]
@ashishitmca is the issue resolved yet?
